steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-west2-docker.pkg.dev/marioarz-sandbox/hello-run/hello-image:tag2 .
  automapSubstitutions: true
images:
- 'us-west2-docker.pkg.dev/marioarz-sandbox/hello-run/hello-image:tag2'
options:
  logging: CLOUD_LOGGING_ONLY