steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/hello-run-2/hello-image:$COMMIT_SHA', '.']
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/hello-run-2/hello-image:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY